<?php
#DO NOT EDIT THIS FILE DIRECTLY!
#IT IS UPDATED BY THE ROUTE PLUGIN WHENEVER YOU ADD, DELETE, ENABLE OR DISABLE A ROUTE.
CroogoRouter::connect('/login', array('plugin' => 'kasse', 'controller' => 'kasse_users', 'action' => 'login'));
CroogoRouter::connect('/register', array('plugin' => 'kasse', 'controller' => 'kasse_users', 'action' => 'add'));
CroogoRouter::connect('/forgot', array('plugin' => 'kasse', 'controller' => 'kasse_users', 'action' => 'forgot'));
CroogoRouter::connect('/reset', array('plugin' => 'kasse', 'controller' => 'kasse_users', 'action' => 'reset'));
CroogoRouter::connect('/logout', array('plugin' => 'kasse', 'controller' => 'kasse_users', 'action' => 'logout'));
